//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerLogApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayerLogDBEntities : DbContext
    {
        public PlayerLogDBEntities()
            : base("name=PlayerLogDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_bolgeler> tbl_bolgeler { get; set; }
        public virtual DbSet<tbl_istatistik> tbl_istatistik { get; set; }
        public virtual DbSet<tbl_istatistikturu> tbl_istatistikturu { get; set; }
        public virtual DbSet<tbl_main> tbl_main { get; set; }
        public virtual DbSet<tbl_oyuncu> tbl_oyuncu { get; set; }
        public virtual DbSet<tbl_takimlar> tbl_takimlar { get; set; }
    }
}
