//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerLogApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_istatistik
    {
        public int ID { get; set; }
        public Nullable<int> OYUNCUID { get; set; }
        public Nullable<int> ISTATISTIKID { get; set; }
        public Nullable<int> MACID { get; set; }
        public Nullable<int> DEGER { get; set; }
    }
}
