//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerLogApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_main
    {
        public int ID { get; set; }
        public int OYUNCUID { get; set; }
        public int BOLGEID { get; set; }
        public int TAKIMID { get; set; }
    
        public virtual tbl_bolgeler tbl_bolgeler { get; set; }
        public virtual tbl_oyuncu tbl_oyuncu { get; set; }
        public virtual tbl_takimlar tbl_takimlar { get; set; }
    }
}
