//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerLogApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_oyuncu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_oyuncu()
        {
            this.tbl_main = new HashSet<tbl_main>();
        }
    
        public int ID { get; set; }
        public int TAKIMID { get; set; }
        public int BOLGEID { get; set; }
        public Nullable<int> OVERALL { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<int> NUMARA { get; set; }
        public Nullable<int> BOY { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string RESIM { get; set; }
    
        public virtual tbl_bolgeler tbl_bolgeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_main> tbl_main { get; set; }
        public virtual tbl_takimlar tbl_takimlar { get; set; }
    }
}
